# docker compose file to run socket-api, socket-ui, and kafka

services:
  socket-api:
    build: ./socket-api
    ports:
      - 3001:3001
  socket-ui:
    build: ./socket-ui
    ports:
      - 3000:3000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - 9092:9092