# docker compose file to run socket-api, socket-ui, nginx, and kafka

services:
  socket-api1:
    build: ./socket-api
    ports:
      - 3001:3001
  socket-api2:
    build: ./socket-api
    ports:
      - 3002:3001
  socket-ui:
    build: ./socket-ui
    ports:
      - 3000:3000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - 9092:9092
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - socket-api1
      - socket-api2